name: webweavex
description: WebWeaveX SDK for Dart and Flutter.
version: 0.1.0
homepage: https://piyush-mishra-00.github.io/WebWeaveX
repository: https://github.com/PIYUSH-MISHRA-00/WebWeaveX
environment:
  sdk: ">=2.19.0 <4.0.0"
dependencies: {}
dev_dependencies:
  test: ^1.30.0
